import logging
import time
import traceback

from starlette.types import ASGIApp, Message, Receive, Scope, Send


def _scrub_headers(headers: dict[str, str]) -> dict[str, str]:
    """Return a copy of headers with Authorization redacted to 'Bearer ***'."""
    scrubbed = dict(headers)
    for key in list(scrubbed.keys()):
        if key.lower() == "authorization":
            scrubbed[key] = "Bearer ***"
    return scrubbed


def _scrub_traceback(exc: Exception) -> str:
    """Format a traceback with frame locals replaced by '<redacted>'.

    Uses traceback.extract_tb to rebuild the traceback string without
    local variable values, preserving file paths, line numbers, function
    names, and the exception type/message.
    """
    extracted = traceback.extract_tb(exc.__traceback__)
    lines: list[str] = []
    lines.append("Traceback (most recent call last):\n")
    for frame in extracted:
        lines.append(
            f'  File "{frame.filename}", line {frame.lineno}, in {frame.name}\n'
        )
        if frame.line:
            lines.append(f"    {frame.line}\n")
    lines.extend(traceback.format_exception_only(type(exc), exc))
    return "".join(lines)


class SuppressUvicornTracebackFilter(logging.Filter):
    """Drop uvicorn.error records that contain exc_info (traceback records).

    Uvicorn emits "Exception in ASGI application" records because
    ServerErrorMiddleware re-raises after the custom exception handler
    runs. This filter drops those redundant tracebacks so the
    middleware's scrubbed traceback is the sole error log.

    Non-traceback error logs (startup errors, config errors, etc.)
    pass through unchanged.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        return record.exc_info is None


request_logger = logging.getLogger("azure_oracle.request")
error_logger = logging.getLogger("azure_oracle.error")


def log_request(method: str, path: str, status_code: int, duration_ms: float) -> None:
    """Emit a request log without recording request or response contents."""
    request_logger.info("%s %s %d %.0fms", method, path, status_code, duration_ms)


def log_unhandled_exception(exc: Exception) -> None:
    """Emit a traceback whose frame locals cannot expose secret values."""
    error_logger.error(
        "Unhandled exception: %s\n%s", type(exc).__name__, _scrub_traceback(exc)
    )


class RequestLoggingMiddleware:
    """Log every non-500 HTTP response without request or response contents.

    Uses two loggers:
    - ``azure_oracle.request`` (INFO) — one line per request
    - ``azure_oracle.error``   (ERROR) — scrubbed traceback from the 500 handler

    A pure ASGI wrapper is required here: ``BaseHTTPMiddleware`` does not see
    responses generated by FastAPI's exception middleware (such as 401 and 403).
    Unhandled exceptions are logged by the server-error handler in ``main.py``,
    which owns the clean 500 response.
    """

    def __init__(self, app: ASGIApp) -> None:
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        start = time.perf_counter()
        scope["state"]["request_start"] = start
        status_code: int | None = None

        async def send_with_logging(message: Message) -> None:
            nonlocal status_code
            if message["type"] == "http.response.start":
                status_code = message["status"]
            await send(message)

        await self.app(scope, receive, send_with_logging)
        if status_code is not None:
            duration_ms = (time.perf_counter() - start) * 1000
            log_request(scope["method"], scope["path"], status_code, duration_ms)